apiVersion: 1

datasources:
  - name: InfluxDB_RiverQuality
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: hydrosense
      defaultBucket: river_water_quality
    secureJsonData:
      token: hydrosense-super-secret-auth-token-123
