# Telegraf Configuration for HydroSense IoT River Monitoring

[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""

# Output Plugin: InfluxDB v2
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "hydrosense-super-secret-auth-token-123"
  organization = "hydrosense"
  bucket = "river_water_quality"

# Input Plugin: MQTT Consumer
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "water-quality/rivers/+/telemetry"
  ]
  qos = 1
  client_id = "telegraf-river-subscriber"
  data_format = "json_v2"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "water-quality/rivers/+/telemetry"
    measurement = "_/_/_/measurement"
    tags = "_/_/riverId/_"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "river_water_quality"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      tags = ["deviceId", "riverId", "riverName"]
      
      [inputs.mqtt_consumer.json_v2.object.fields]
        "telemetry_oxygenSaturationPct" = "float"
        "telemetry_dissolvedOxygenMgl" = "float"
        "telemetry_waterTempC" = "float"
        "telemetry_ph" = "float"
        "status_batteryPct" = "int"
        "status_hypoxiaWarning" = "bool"
